#!/usr/bin/env python3
"""
統合M系列信号配列生成スクリプト
MATLABで生成されたCSVファイルからESP32用C++配列を生成

機能:
- 複数のサイズ選択（100, 1000, 5000, 10000, 40950サンプル）
- メモリ使用量計算と警告
- 段階的な配列生成
- ESP32設定ガイド付き
"""

import csv
import os
import sys
from typing import List, Tuple, Optional

class SignalArrayGenerator:
    """M系列信号配列生成クラス"""

    # サイズプリセット
    SIZE_PRESETS = {
        'tiny': 100,      # テスト用（0.1秒）
        'small': 1000,    # 短時間実験（1秒）
        'medium': 5000,   # 中程度実験（5秒）
        'large': 10000,   # 長時間実験（10秒）
        'full': 40950     # フルスケール実験（40.95秒）
    }

    def __init__(self):
        self.translation_file = "Mcode/translation_input.txt"
        self.rotation_file = "Mcode/rotation_input.txt"

    def read_signal_file(self, filename: str) -> Tuple[Optional[List[float]], Optional[List[float]]]:
        """CSVファイルから信号データを読み込む"""
        left_signals = []
        right_signals = []

        try:
            print(f"Reading {filename}...")
            with open(filename, 'r') as file:
                reader = csv.DictReader(file)
                for row in reader:
                    left_signals.append(float(row['u_left']))
                    right_signals.append(float(row['u_right']))

            print(f"Successfully read {len(left_signals)} samples from {filename}")
            return left_signals, right_signals

        except FileNotFoundError:
            print(f"Error: File {filename} not found!")
            print("Make sure MATLAB files are generated and placed in Mcode/ directory")
            return None, None
        except Exception as e:
            print(f"Error reading {filename}: {e}")
            return None, None

    def calculate_memory_usage(self, num_samples: int) -> Tuple[int, float]:
        """メモリ使用量を計算"""
        # 4つの配列（trans_left, trans_right, rot_left, rot_right）× 4バイト/float
        memory_bytes = num_samples * 4 * 4
        memory_kb = memory_bytes / 1024.0
        return memory_bytes, memory_kb

    def generate_cpp_array(self, signals: List[float], array_name: str,
                          max_samples: Optional[int] = None) -> str:
        """C++配列コードを生成する"""
        if max_samples and len(signals) > max_samples:
            signals = signals[:max_samples]
            print(f"Truncated {array_name} to {max_samples} samples")

        cpp_code = f"// {len(signals)} samples\n"
        cpp_code += f"static const float {array_name}[{len(signals)}] = {{\n"

        # 10個ずつの行で整理
        for i in range(0, len(signals), 10):
            line_data = signals[i:i+10]
            line_str = ", ".join(f"{val:8.6f}f" for val in line_data)
            cpp_code += f"    {line_str}"
            if i + 10 < len(signals):
                cpp_code += ","
            cpp_code += "\n"

            # 進捗表示（大きなファイルの場合）
            if len(signals) > 5000 and i % 5000 == 0 and i > 0:
                print(f"Generating {array_name}: {i}/{len(signals)} samples...")

        cpp_code += "};\n\n"
        return cpp_code

    def generate_header_file(self, trans_left: List[float], trans_right: List[float],
                           rot_left: List[float], rot_right: List[float],
                           max_samples: int, output_file: str) -> None:
        """ヘッダーファイルを生成"""

        memory_bytes, memory_kb = self.calculate_memory_usage(max_samples)
        experiment_duration = max_samples * 0.001

        # ファイル名に基づく命名
        if 'embedded_signals' in output_file:
            namespace_name = "SystemIdentificationSignals"
            array_suffix = f"{max_samples}"
        else:
            namespace_name = "FullSizeSignals"
            array_suffix = f"{max_samples}"

        cpp_output = f"""// ESP32組み込み用M系列信号データ
// MATLABのrobot_system_identification_input.mで生成されたデータから抽出
// Generated by generate_signal_arrays.py

#ifndef {"EMBEDDED_SIGNALS_HPP" if 'embedded_signals' in output_file else "FULLSIZE_SIGNALS_HPP"}
#define {"EMBEDDED_SIGNALS_HPP" if 'embedded_signals' in output_file else "FULLSIZE_SIGNALS_HPP"}

// システム同定用埋め込み信号データ
namespace {namespace_name} {{

"""

        print("Generating C++ arrays...")

        cpp_output += self.generate_cpp_array(trans_left, f"translation_signal_left_{array_suffix}", max_samples)
        cpp_output += self.generate_cpp_array(trans_right, f"translation_signal_right_{array_suffix}", max_samples)
        cpp_output += self.generate_cpp_array(rot_left, f"rotation_signal_left_{array_suffix}", max_samples)
        cpp_output += self.generate_cpp_array(rot_right, f"rotation_signal_right_{array_suffix}", max_samples)

        cpp_output += f"""// サンプル数定数
static constexpr int {"FULL_SCALE_SAMPLES" if max_samples <= 1000 else "FULLSIZE_SAMPLES"} = {max_samples};
static constexpr int SAMPLING_PERIOD_MS = 1;  // 1ms
static constexpr float EXPERIMENT_DURATION_SEC = {experiment_duration:.3f}f;  // seconds

}} // namespace {namespace_name}

#endif // {"EMBEDDED_SIGNALS_HPP" if 'embedded_signals' in output_file else "FULLSIZE_SIGNALS_HPP"}

/*
=== 使用方法 ===

1. test.hppに追加:
#include "../{os.path.basename(output_file)}"

2. test.cppで使用:
motion.RunTranslationIdentification(
    {namespace_name}::translation_signal_left_{array_suffix},
    {namespace_name}::translation_signal_right_{array_suffix},
    {namespace_name}::{"FULL_SCALE_SAMPLES" if max_samples <= 1000 else "FULLSIZE_SAMPLES"},
    {namespace_name}::SAMPLING_PERIOD_MS
);

=== ESP32設定 ===
"""

        if memory_kb > 100:
            cpp_output += f"""
PSRAM必要（大容量配列のため）:
idf.py menuconfig → Component config → ESP32-specific → Support for external SPI RAM

sdkconfig設定:
CONFIG_ESP32_SPIRAM_SUPPORT=y
CONFIG_SPIRAM_USE=y
CONFIG_SPIRAM_TYPE_AUTO=y
CONFIG_SPIRAM_USE_MALLOC=y
"""
        else:
            cpp_output += f"""
通常のRAMで使用可能:
追加設定不要
"""

        cpp_output += f"""
=== 仕様 ===
配列数: 4個（translation_left/right, rotation_left/right）
サンプル数: {max_samples}個
メモリ使用量: {memory_kb:.1f} KB
実験時間: {experiment_duration:.1f}秒

=== 安全性 ===
- 最大duty比: ±0.3に制限
- 実験前のメモリチェック推奨
- 長時間実験は安全な環境で実施
*/
"""

        # ファイルに出力
        os.makedirs(os.path.dirname(output_file), exist_ok=True)
        with open(output_file, 'w') as f:
            f.write(cpp_output)

        print(f"\n✓ Generated {output_file}")
        print(f"✓ Arrays contain {max_samples} samples each")
        print(f"✓ Memory usage: {memory_kb:.1f} KB")
        print(f"✓ Experiment duration: {experiment_duration:.1f} seconds")

    def display_menu(self) -> None:
        """メニューを表示"""
        print("=" * 60)
        print("ESP32用M系列信号配列生成ツール")
        print("=" * 60)
        print("\n利用可能なサイズプリセット:")

        for i, (name, samples) in enumerate(self.SIZE_PRESETS.items(), 1):
            memory_bytes, memory_kb = self.calculate_memory_usage(samples)
            duration = samples * 0.001

            print(f"{i}. {name:8} : {samples:5}サンプル ({memory_kb:6.1f}KB, {duration:5.1f}秒)")

            # メモリ要件の注意
            if memory_kb > 200:
                print(f"           → PSRAMまたは外部ストレージ必須")
            elif memory_kb > 50:
                print(f"           → ESP32-WROVER推奨")
            else:
                print(f"           → 標準ESP32で使用可能")

        print(f"{len(self.SIZE_PRESETS) + 1}. custom  : カスタムサイズ指定")
        print(f"{len(self.SIZE_PRESETS) + 2}. all     : 複数サイズを一括生成")

    def get_user_choice(self) -> Tuple[str, int]:
        """ユーザーの選択を取得"""
        self.display_menu()

        try:
            choice = input(f"\n選択 (1-{len(self.SIZE_PRESETS) + 2}): ").strip()

            if choice.isdigit():
                choice_num = int(choice)
                if 1 <= choice_num <= len(self.SIZE_PRESETS):
                    preset_name = list(self.SIZE_PRESETS.keys())[choice_num - 1]
                    return preset_name, self.SIZE_PRESETS[preset_name]
                elif choice_num == len(self.SIZE_PRESETS) + 1:
                    # カスタムサイズ
                    custom_size = int(input("カスタムサイズ（サンプル数）: "))
                    return "custom", custom_size
                elif choice_num == len(self.SIZE_PRESETS) + 2:
                    # 一括生成
                    return "all", 0

            print("無効な選択です。")
            return self.get_user_choice()

        except (ValueError, KeyboardInterrupt):
            print("\n終了します。")
            sys.exit(0)

    def confirm_generation(self, preset_name: str, samples: int) -> bool:
        """生成の確認"""
        memory_bytes, memory_kb = self.calculate_memory_usage(samples)
        duration = samples * 0.001

        print(f"\n=== 生成確認 ===")
        print(f"プリセット: {preset_name}")
        print(f"サンプル数: {samples:,}")
        print(f"メモリ使用量: {memory_kb:.1f} KB")
        print(f"実験時間: {duration:.1f} 秒")

        if memory_kb > 200:
            print(f"\n⚠️  警告: 大容量配列です！")
            print(f"   ESP32-WROVERとPSRAMが必要です")
        elif memory_kb > 50:
            print(f"\n⚠️  注意: 中容量配列です")
            print(f"   ESP32-WROVERを推奨します")

        response = input("\n生成を続行しますか？ (y/N): ").strip().lower()
        return response in ['y', 'yes']

    def generate_single(self, preset_name: str, samples: int) -> None:
        """単一サイズの配列を生成"""

        if not self.confirm_generation(preset_name, samples):
            print("キャンセルされました。")
            return

        # データ読み込み
        trans_left, trans_right = self.read_signal_file(self.translation_file)
        if trans_left is None:
            return

        rot_left, rot_right = self.read_signal_file(self.rotation_file)
        if rot_left is None:
            return

        print(f"元データ: 並進={len(trans_left):,}, 回転={len(rot_left):,} サンプル")

        # 出力ファイル名を決定
        if samples <= 1000:
            output_file = "main/include/embedded_signals.hpp"
        else:
            output_file = "main/include/fullsize_signals.hpp"

        # ヘッダーファイル生成
        self.generate_header_file(trans_left, trans_right, rot_left, rot_right,
                                samples, output_file)

        # 次のステップを表示
        self.show_next_steps(output_file, samples)

    def generate_all(self) -> None:
        """全サイズを一括生成"""
        print("\n=== 一括生成モード ===")
        print("複数のサイズの配列を生成します")

        # 生成するサイズを選択
        sizes_to_generate = ['tiny', 'small']  # デフォルト

        response = input("中・大・フルサイズも生成しますか？ (y/N): ").strip().lower()
        if response in ['y', 'yes']:
            sizes_to_generate.extend(['medium', 'large', 'full'])

        # データ読み込み（一度だけ）
        print("\nMATLABファイルを読み込み中...")
        trans_left, trans_right = self.read_signal_file(self.translation_file)
        if trans_left is None:
            return

        rot_left, rot_right = self.read_signal_file(self.rotation_file)
        if rot_left is None:
            return

        print(f"元データ: 並進={len(trans_left):,}, 回転={len(rot_left):,} サンプル")

        # 各サイズを生成
        for preset_name in sizes_to_generate:
            samples = self.SIZE_PRESETS[preset_name]
            memory_bytes, memory_kb = self.calculate_memory_usage(samples)

            print(f"\n--- {preset_name}サイズ生成中 ({samples} samples, {memory_kb:.1f}KB) ---")

            # 出力ファイル名を決定
            if samples <= 1000:
                output_file = f"main/include/embedded_signals_{preset_name}.hpp"
            else:
                output_file = f"main/include/fullsize_signals_{preset_name}.hpp"

            # ヘッダーファイル生成
            self.generate_header_file(trans_left, trans_right, rot_left, rot_right,
                                    samples, output_file)

        print(f"\n✓ 一括生成完了！ {len(sizes_to_generate)}個のファイルを生成しました")
        self.show_batch_next_steps()

    def show_next_steps(self, output_file: str, samples: int) -> None:
        """次のステップを表示"""
        print(f"\n=== 次のステップ ===")
        print(f"1. test.hppに追加:")
        print(f"   #include \"../{os.path.basename(output_file)}\"")
        print(f"")
        print(f"2. ESP32設定（{samples}サンプルの場合）:")

        memory_bytes, memory_kb = self.calculate_memory_usage(samples)
        if memory_kb > 100:
            print(f"   idf.py menuconfig")
            print(f"   → Component config → ESP32-specific → Support for external SPI RAM")
        else:
            print(f"   追加設定は不要です")

        print(f"")
        print(f"3. ビルドとテスト:")
        print(f"   idf.py build")

    def show_batch_next_steps(self) -> None:
        """一括生成後の次のステップを表示"""
        print(f"\n=== 一括生成後の使用方法 ===")
        print(f"各サイズに応じて適切なヘッダーファイルをインクルードしてください:")
        print(f"")
        print(f"// 小サイズ用（≤1000サンプル）")
        print(f"#include \"../embedded_signals_tiny.hpp\"    // 100サンプル")
        print(f"#include \"../embedded_signals_small.hpp\"   // 1000サンプル")
        print(f"")
        print(f"// 大サイズ用（>1000サンプル、PSRAM必要）")
        print(f"#include \"../fullsize_signals_medium.hpp\"  // 5000サンプル")
        print(f"#include \"../fullsize_signals_large.hpp\"   // 10000サンプル")
        print(f"#include \"../fullsize_signals_full.hpp\"    // 40950サンプル")

    def run(self) -> None:
        """メインの実行関数"""
        try:
            # MATLABファイルの存在確認
            if not os.path.exists(self.translation_file):
                print(f"Error: {self.translation_file} が見つかりません")
                print("MATLABでrobot_system_identification_input.mを実行してファイルを生成してください")
                return

            if not os.path.exists(self.rotation_file):
                print(f"Error: {self.rotation_file} が見つかりません")
                print("MATLABでrobot_system_identification_input.mを実行してファイルを生成してください")
                return

            # ユーザー選択
            preset_name, samples = self.get_user_choice()

            if preset_name == "all":
                self.generate_all()
            else:
                self.generate_single(preset_name, samples)

        except KeyboardInterrupt:
            print("\n\n中断されました。")
        except Exception as e:
            print(f"\nエラーが発生しました: {e}")
            import traceback
            traceback.print_exc()

def main():
    """メイン関数"""
    generator = SignalArrayGenerator()
    generator.run()

if __name__ == "__main__":
    main()